name: CI
on:
  push:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: anishathalye/proof-html@v2
        with:
          directory: ./
          enforce_https: false
          check_html: true
          check_favicon: false
          ignore_url: |
            https://fonts.googleapis.com/css?family=Martel+Sans&display=swap
            https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
            https://fonts.googleapis.com
            https://fonts.gstatic.com
          ignore_url_re: |
            ^https://twitter.com/
            ^/challenges/